// CUSTOMERS------------------------------------------------------
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS'
export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START'
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'
export const FETCH_CUSTOMERS_FAIL = 'FETCH_CUSTOMERS_FAIL'

export const CREATE_CUSTOMER = 'CREATE_CUSTOMER'
export const CREATE_CUSTOMER_START = 'CREATE_CUSTOMER_START'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_FAIL = 'CREATE_CUSTOMER_FAIL'

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'
export const DELETE_CUSTOMER_START = 'DELETE_CUSTOMER_START'
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS'
export const DELETE_CUSTOMER_FAIL = 'DELETE_CUSTOMER_FAIL'

export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'
export const UPDATE_CUSTOMER_START = 'UPDATE_CUSTOMER_START'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_FAIL = 'UPDATE_CUSTOMER_FAIL'

// ASSETS------------------------------------------------------
export const FETCH_ASSETS = 'FETCH_ASSETS'
export const FETCH_ASSETS_START = 'FETCH_ASSETS_START'
export const FETCH_ASSETS_SUCCESS = 'FETCH_ASSETS_SUCCESS'
export const FETCH_ASSETS_FAIL = 'FETCH_ASSETS_FAIL'

export const CREATE_ASSET = 'CREATE_ASSET'
export const CREATE_ASSET_START = 'CREATE_ASSET_START'
export const CREATE_ASSET_SUCCESS = 'CREATE_ASSET_SUCCESS'
export const CREATE_ASSET_FAIL = 'CREATE_ASSET_FAIL'

export const DELETE_ASSET = 'DELETE_ASSET'
export const DELETE_ASSET_START = 'DELETE_ASSET_START'
export const DELETE_ASSET_SUCCESS = 'DELETE_ASSET_SUCCESS'
export const DELETE_ASSET_FAIL = 'DELETE_ASSET_FAIL'

export const UPDATE_ASSET = 'UPDATE_ASSET'
export const UPDATE_ASSET_START = 'UPDATE_ASSET_START'
export const UPDATE_ASSET_SUCCESS = 'UPDATE_ASSET_SUCCESS'
export const UPDATE_ASSET_FAIL = 'UPDATE_ASSET_FAIL'

// APPTS------------------------------------------------------
export const FETCH_APPTS = 'FETCH_APPTS'
export const FETCH_APPTS_START = 'FETCH_APPTS_START'
export const FETCH_APPTS_SUCCESS = 'FETCH_APPTS_SUCCESS'
export const FETCH_APPTS_FAIL = 'FETCH_APPTS_FAIL'

export const CREATE_APPT = 'CREATE_APPT'
export const CREATE_APPT_START = 'CREATE_APPT_START'
export const CREATE_APPT_SUCCESS = 'CREATE_APPT_SUCCESS'
export const CREATE_APPT_FAIL = 'CREATE_APPT_FAIL'

export const DELETE_APPT = 'DELETE_APPT'
export const DELETE_APPT_START = 'DELETE_APPT_START'
export const DELETE_APPT_SUCCESS = 'DELETE_APPT_SUCCESS'
export const DELETE_APPT_FAIL = 'DELETE_APPT_FAIL'

export const UPDATE_APPT = 'UPDATE_APPT'
export const UPDATE_APPT_START = 'UPDATE_APPT_START'
export const UPDATE_APPT_SUCCESS = 'UPDATE_APPT_SUCCESS'
export const UPDATE_APPT_FAIL = 'UPDATE_APPT_FAIL'

// SERVICES------------------------------------------------------
export const FETCH_SERVICES = 'FETCH_SERVICES'
export const FETCH_SERVICES_START = 'FETCH_SERVICES_START'
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS'
export const FETCH_SERVICES_FAIL = 'FETCH_SERVICES_FAIL'

export const CREATE_SERVICE = 'CREATE_SERVICE'
export const CREATE_SERVICE_START = 'CREATE_SERVICE_START'
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS'
export const CREATE_SERVICE_FAIL = 'CREATE_SERVICE_FAIL'

export const DELETE_SERVICE = 'DELETE_SERVICE'
export const DELETE_SERVICE_START = 'DELETE_SERVICE_START'
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS'
export const DELETE_SERVICE_FAIL = 'DELETE_SERVICE_FAIL'

export const UPDATE_SERVICE = 'UPDATE_SERVICE'
export const UPDATE_SERVICE_START = 'UPDATE_SERVICE_START'
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS'
export const UPDATE_SERVICE_FAIL = 'UPDATE_SERVICE_FAIL'

